// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGPR1BCytR0CM0-2lJkDPQx964c2RPC7w',
    appId: '1:182223019751:android:9ef534b6ee37f4a172cc42',
    messagingSenderId: '182223019751',
    projectId: 'ecommerceapp-74910',
    databaseURL: 'https://ecommerceapp-74910-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-74910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7TBBFlZYPhr74svTDBxQNR5EUBHkvI1Q',
    appId: '1:182223019751:ios:87e0f1a1db11fa7a72cc42',
    messagingSenderId: '182223019751',
    projectId: 'ecommerceapp-74910',
    databaseURL: 'https://ecommerceapp-74910-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-74910.appspot.com',
    androidClientId: '182223019751-fp3bvguuf2l6cajnirh3m1drhovdirji.apps.googleusercontent.com',
    iosClientId: '182223019751-5md0k5c9jmphnoiikpcfb0ljmrh64b7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
